more changes to order list
chingu-voyages/v50-tier2-team-16 pull request #105
Opened 2024-08-09 05:26 UTC by MatthewNeie

2024-08-09 14:34 UTC, arositen requested changes
New styles look good, we should get rid of checkout button and Total pointed out on the screenshot though, since we already have working implementations

![image](https://github.com/user-attachments/assets/4c3e6e5f-b69d-4011-95fe-0837a188d46e)

2024-08-09 23:14 UTC, MatthewNeie commented
changes made.

2024-08-10 02:51 UTC, arositen approved these changes

2024-08-10 06:26 UTC, kristi-h approved these changes

2024-08-10 06:26 UTC, merged